// Repository tokens
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';
export const QUESTION_VERSION_REPOSITORY = 'QUESTION_VERSION_REPOSITORY';
export const QUESTION_IMAGE_REPOSITORY = 'QUESTION_IMAGE_REPOSITORY';
export const QUESTION_TAG_REPOSITORY = 'QUESTION_TAG_REPOSITORY';

// Service tokens
export const QUESTION_SERVICE = 'QUESTION_SERVICE';
export const QUESTION_VERSION_SERVICE = 'QUESTION_VERSION_SERVICE'; 