version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nynus_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nynus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nynus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  nynus_network:
    driver: bridge 